POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjYzZjMyY2E5MmY2MTMwODdhYzkyZGU0ZCIsIm5hbWUiOiJ1c2VyIiwiaWF0IjoxNjc2ODgxNjUzLCJleHAiOjE2NzY4OTI0NTN9.2YFVFgTQEEtPVjvx-kBB82L1Ekh9rodqf7yB2rQ_UWI

{
    "title":"first note",
    "body":"Body of the first note"
}
