GET http://localhost:3001/api/notes/63f1010c9033a2dbceee6fac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9sYXMiLCJpZCI6IjYzZjBmMmQ0ZjRjMzAzMzdhYTk5Nzg0OSIsIm5hbWUiOiJPbGFveWUgQmFscWlzIiwiaWF0IjoxNjc2ODM5NTY2LCJleHAiOjE2NzY4NTAzNjZ9.ft4wHeeeh_wZBVd0qbEyueVMFHMAdzMWI7NPZ9kRo4I
